// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: abilities.sql

package dbgen

import (
	"context"
)

const createAbility = `-- name: CreateAbility :exec
INSERT INTO abilities (
    group_name, alias_model, channel_id, upstream_model, priority, weight, enabled
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAbilityParams struct {
	GroupName     string `json:"group_name"`
	AliasModel    string `json:"alias_model"`
	ChannelID     int64  `json:"channel_id"`
	UpstreamModel string `json:"upstream_model"`
	Priority      int64  `json:"priority"`
	Weight        int64  `json:"weight"`
	Enabled       int64  `json:"enabled"`
}

func (q *Queries) CreateAbility(ctx context.Context, arg CreateAbilityParams) error {
	_, err := q.db.ExecContext(ctx, createAbility,
		arg.GroupName,
		arg.AliasModel,
		arg.ChannelID,
		arg.UpstreamModel,
		arg.Priority,
		arg.Weight,
		arg.Enabled,
	)
	return err
}

const deleteAbilitiesForChannel = `-- name: DeleteAbilitiesForChannel :exec

DELETE FROM abilities WHERE channel_id = ?
`

// Abilities (derived routing index). On channel save, in one tx:
// DeleteAbilitiesForChannel then CreateAbility per row (incremental, never TRUNCATE).
// On startup, ListEnabledAbilities builds the in-memory RouteIndex.
// ASCII comments on purpose (sqlc CJK parser limitation).
func (q *Queries) DeleteAbilitiesForChannel(ctx context.Context, channelID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAbilitiesForChannel, channelID)
	return err
}

const listAbilitiesForChannel = `-- name: ListAbilitiesForChannel :many
SELECT group_name, alias_model, channel_id, upstream_model, priority, weight, enabled FROM abilities WHERE channel_id = ?
`

func (q *Queries) ListAbilitiesForChannel(ctx context.Context, channelID int64) ([]Ability, error) {
	rows, err := q.db.QueryContext(ctx, listAbilitiesForChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ability{}
	for rows.Next() {
		var i Ability
		if err := rows.Scan(
			&i.GroupName,
			&i.AliasModel,
			&i.ChannelID,
			&i.UpstreamModel,
			&i.Priority,
			&i.Weight,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAbilities = `-- name: ListEnabledAbilities :many
SELECT group_name, alias_model, channel_id, upstream_model, priority, weight, enabled FROM abilities WHERE enabled = 1
`

func (q *Queries) ListEnabledAbilities(ctx context.Context) ([]Ability, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledAbilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ability{}
	for rows.Next() {
		var i Ability
		if err := rows.Scan(
			&i.GroupName,
			&i.AliasModel,
			&i.ChannelID,
			&i.UpstreamModel,
			&i.Priority,
			&i.Weight,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
