// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createAPIKey = `-- name: CreateAPIKey :one

INSERT INTO api_keys (hash, name, group_name, enabled, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, hash, name, group_name, enabled, created_at, last_used_at
`

type CreateAPIKeyParams struct {
	Hash      string `json:"hash"`
	Name      string `json:"name"`
	GroupName string `json:"group_name"`
	Enabled   int64  `json:"enabled"`
	CreatedAt string `json:"created_at"`
}

// Inbound API keys. Only the sha256 hash is stored; GetAPIKeyByHash backs auth.
// ASCII comments on purpose (sqlc CJK parser limitation).
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.Hash,
		arg.Name,
		arg.GroupName,
		arg.Enabled,
		arg.CreatedAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Name,
		&i.GroupName,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = ?
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, id)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, hash, name, group_name, enabled, created_at, last_used_at FROM api_keys WHERE hash = ?
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, hash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, hash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Name,
		&i.GroupName,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, hash, name, group_name, enabled, created_at, last_used_at FROM api_keys ORDER BY id ASC
`

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.Name,
			&i.GroupName,
			&i.Enabled,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAPIKeyEnabled = `-- name: SetAPIKeyEnabled :exec
UPDATE api_keys SET enabled = ? WHERE id = ?
`

type SetAPIKeyEnabledParams struct {
	Enabled int64 `json:"enabled"`
	ID      int64 `json:"id"`
}

func (q *Queries) SetAPIKeyEnabled(ctx context.Context, arg SetAPIKeyEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setAPIKeyEnabled, arg.Enabled, arg.ID)
	return err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = ? WHERE id = ?
`

type TouchAPIKeyLastUsedParams struct {
	LastUsedAt sql.NullString `json:"last_used_at"`
	ID         int64          `json:"id"`
}

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, arg TouchAPIKeyLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, touchAPIKeyLastUsed, arg.LastUsedAt, arg.ID)
	return err
}
