// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package dbgen

import (
	"context"
)

const createChannel = `-- name: CreateChannel :one

INSERT INTO channels (
    name, enabled, platform, type, base_url, group_name, priority, weight,
    models, model_mapping, prefix, proxy_url, status, error_message, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, name, enabled, platform, type, base_url, group_name, priority, weight, models, model_mapping, prefix, proxy_url, status, error_message, created_at, updated_at
`

type CreateChannelParams struct {
	Name         string `json:"name"`
	Enabled      int64  `json:"enabled"`
	Platform     string `json:"platform"`
	Type         string `json:"type"`
	BaseUrl      string `json:"base_url"`
	GroupName    string `json:"group_name"`
	Priority     int64  `json:"priority"`
	Weight       int64  `json:"weight"`
	Models       string `json:"models"`
	ModelMapping string `json:"model_mapping"`
	Prefix       string `json:"prefix"`
	ProxyUrl     string `json:"proxy_url"`
	Status       string `json:"status"`
	ErrorMessage string `json:"error_message"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

// Channel CRUD. Reads use store.Read(); writes use store.Write().
// NOTE: comments here are ASCII on purpose -- sqlc's SQLite parser mis-handles
// multibyte (CJK) characters in query files. Chinese docs live in the Go dao layer.
func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createChannel,
		arg.Name,
		arg.Enabled,
		arg.Platform,
		arg.Type,
		arg.BaseUrl,
		arg.GroupName,
		arg.Priority,
		arg.Weight,
		arg.Models,
		arg.ModelMapping,
		arg.Prefix,
		arg.ProxyUrl,
		arg.Status,
		arg.ErrorMessage,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Platform,
		&i.Type,
		&i.BaseUrl,
		&i.GroupName,
		&i.Priority,
		&i.Weight,
		&i.Models,
		&i.ModelMapping,
		&i.Prefix,
		&i.ProxyUrl,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels WHERE id = ?
`

func (q *Queries) DeleteChannel(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteChannel, id)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT id, name, enabled, platform, type, base_url, group_name, priority, weight, models, model_mapping, prefix, proxy_url, status, error_message, created_at, updated_at FROM channels WHERE id = ?
`

func (q *Queries) GetChannel(ctx context.Context, id int64) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Platform,
		&i.Type,
		&i.BaseUrl,
		&i.GroupName,
		&i.Priority,
		&i.Weight,
		&i.Models,
		&i.ModelMapping,
		&i.Prefix,
		&i.ProxyUrl,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT id, name, enabled, platform, type, base_url, group_name, priority, weight, models, model_mapping, prefix, proxy_url, status, error_message, created_at, updated_at FROM channels ORDER BY priority DESC, id ASC
`

func (q *Queries) ListChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.Platform,
			&i.Type,
			&i.BaseUrl,
			&i.GroupName,
			&i.Priority,
			&i.Weight,
			&i.Models,
			&i.ModelMapping,
			&i.Prefix,
			&i.ProxyUrl,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledChannels = `-- name: ListEnabledChannels :many
SELECT id, name, enabled, platform, type, base_url, group_name, priority, weight, models, model_mapping, prefix, proxy_url, status, error_message, created_at, updated_at FROM channels WHERE enabled = 1 ORDER BY priority DESC, id ASC
`

func (q *Queries) ListEnabledChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.Platform,
			&i.Type,
			&i.BaseUrl,
			&i.GroupName,
			&i.Priority,
			&i.Weight,
			&i.Models,
			&i.ModelMapping,
			&i.Prefix,
			&i.ProxyUrl,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChannelStatus = `-- name: SetChannelStatus :exec
UPDATE channels SET status = ?, error_message = ?, updated_at = ? WHERE id = ?
`

type SetChannelStatusParams struct {
	Status       string `json:"status"`
	ErrorMessage string `json:"error_message"`
	UpdatedAt    string `json:"updated_at"`
	ID           int64  `json:"id"`
}

func (q *Queries) SetChannelStatus(ctx context.Context, arg SetChannelStatusParams) error {
	_, err := q.db.ExecContext(ctx, setChannelStatus,
		arg.Status,
		arg.ErrorMessage,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels SET
    name = ?, enabled = ?, platform = ?, type = ?, base_url = ?, group_name = ?,
    priority = ?, weight = ?, models = ?, model_mapping = ?, prefix = ?, proxy_url = ?,
    status = ?, error_message = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, enabled, platform, type, base_url, group_name, priority, weight, models, model_mapping, prefix, proxy_url, status, error_message, created_at, updated_at
`

type UpdateChannelParams struct {
	Name         string `json:"name"`
	Enabled      int64  `json:"enabled"`
	Platform     string `json:"platform"`
	Type         string `json:"type"`
	BaseUrl      string `json:"base_url"`
	GroupName    string `json:"group_name"`
	Priority     int64  `json:"priority"`
	Weight       int64  `json:"weight"`
	Models       string `json:"models"`
	ModelMapping string `json:"model_mapping"`
	Prefix       string `json:"prefix"`
	ProxyUrl     string `json:"proxy_url"`
	Status       string `json:"status"`
	ErrorMessage string `json:"error_message"`
	UpdatedAt    string `json:"updated_at"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, updateChannel,
		arg.Name,
		arg.Enabled,
		arg.Platform,
		arg.Type,
		arg.BaseUrl,
		arg.GroupName,
		arg.Priority,
		arg.Weight,
		arg.Models,
		arg.ModelMapping,
		arg.Prefix,
		arg.ProxyUrl,
		arg.Status,
		arg.ErrorMessage,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Platform,
		&i.Type,
		&i.BaseUrl,
		&i.GroupName,
		&i.Priority,
		&i.Weight,
		&i.Models,
		&i.ModelMapping,
		&i.Prefix,
		&i.ProxyUrl,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
