// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package dbgen

import (
	"context"
	"database/sql"
)

const getChannelModelHealth = `-- name: GetChannelModelHealth :one
SELECT channel_id, model, is_healthy, consecutive_failures, last_success_at, last_failure_at, last_error, cooldown_until, updated_at FROM channel_model_health WHERE channel_id = ? AND model = ?
`

type GetChannelModelHealthParams struct {
	ChannelID int64  `json:"channel_id"`
	Model     string `json:"model"`
}

func (q *Queries) GetChannelModelHealth(ctx context.Context, arg GetChannelModelHealthParams) (ChannelModelHealth, error) {
	row := q.db.QueryRowContext(ctx, getChannelModelHealth, arg.ChannelID, arg.Model)
	var i ChannelModelHealth
	err := row.Scan(
		&i.ChannelID,
		&i.Model,
		&i.IsHealthy,
		&i.ConsecutiveFailures,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.LastError,
		&i.CooldownUntil,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannelModelHealth = `-- name: ListChannelModelHealth :many
SELECT channel_id, model, is_healthy, consecutive_failures, last_success_at, last_failure_at, last_error, cooldown_until, updated_at FROM channel_model_health
`

func (q *Queries) ListChannelModelHealth(ctx context.Context) ([]ChannelModelHealth, error) {
	rows, err := q.db.QueryContext(ctx, listChannelModelHealth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelModelHealth{}
	for rows.Next() {
		var i ChannelModelHealth
		if err := rows.Scan(
			&i.ChannelID,
			&i.Model,
			&i.IsHealthy,
			&i.ConsecutiveFailures,
			&i.LastSuccessAt,
			&i.LastFailureAt,
			&i.LastError,
			&i.CooldownUntil,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertChannelModelHealth = `-- name: UpsertChannelModelHealth :exec

INSERT INTO channel_model_health (
    channel_id, model, is_healthy, consecutive_failures,
    last_success_at, last_failure_at, last_error, cooldown_until, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (channel_id, model) DO UPDATE SET
    is_healthy = excluded.is_healthy,
    consecutive_failures = excluded.consecutive_failures,
    last_success_at = excluded.last_success_at,
    last_failure_at = excluded.last_failure_at,
    last_error = excluded.last_error,
    cooldown_until = excluded.cooldown_until,
    updated_at = excluded.updated_at
`

type UpsertChannelModelHealthParams struct {
	ChannelID           int64          `json:"channel_id"`
	Model               string         `json:"model"`
	IsHealthy           int64          `json:"is_healthy"`
	ConsecutiveFailures int64          `json:"consecutive_failures"`
	LastSuccessAt       sql.NullString `json:"last_success_at"`
	LastFailureAt       sql.NullString `json:"last_failure_at"`
	LastError           string         `json:"last_error"`
	CooldownUntil       sql.NullString `json:"cooldown_until"`
	UpdatedAt           string         `json:"updated_at"`
}

// Passive per (channel, model) health/cooldown. MarkResult upserts; selector reads
// the in-memory mirror loaded via ListChannelModelHealth at startup.
// ASCII comments on purpose (sqlc CJK parser limitation).
func (q *Queries) UpsertChannelModelHealth(ctx context.Context, arg UpsertChannelModelHealthParams) error {
	_, err := q.db.ExecContext(ctx, upsertChannelModelHealth,
		arg.ChannelID,
		arg.Model,
		arg.IsHealthy,
		arg.ConsecutiveFailures,
		arg.LastSuccessAt,
		arg.LastFailureAt,
		arg.LastError,
		arg.CooldownUntil,
		arg.UpdatedAt,
	)
	return err
}
