// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health_checks.sql

package dbgen

import (
	"context"
)

const deleteHealthChecksBefore = `-- name: DeleteHealthChecksBefore :execrows
DELETE FROM health_check_logs WHERE checked_at < ?
`

func (q *Queries) DeleteHealthChecksBefore(ctx context.Context, checkedAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHealthChecksBefore, checkedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertHealthCheck = `-- name: InsertHealthCheck :exec

INSERT INTO health_check_logs (
    channel_id, model, success, http_status, response_time_ms, message, checked_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertHealthCheckParams struct {
	ChannelID      int64  `json:"channel_id"`
	Model          string `json:"model"`
	Success        int64  `json:"success"`
	HttpStatus     int64  `json:"http_status"`
	ResponseTimeMs int64  `json:"response_time_ms"`
	Message        string `json:"message"`
	CheckedAt      string `json:"checked_at"`
}

// health_check_logs queries (active probe). ASCII-only comments.
func (q *Queries) InsertHealthCheck(ctx context.Context, arg InsertHealthCheckParams) error {
	_, err := q.db.ExecContext(ctx, insertHealthCheck,
		arg.ChannelID,
		arg.Model,
		arg.Success,
		arg.HttpStatus,
		arg.ResponseTimeMs,
		arg.Message,
		arg.CheckedAt,
	)
	return err
}

const listRecentHealthChecks = `-- name: ListRecentHealthChecks :many
SELECT id, channel_id, model, success, http_status, response_time_ms, message, checked_at FROM health_check_logs ORDER BY checked_at DESC, id DESC LIMIT ?
`

func (q *Queries) ListRecentHealthChecks(ctx context.Context, limit int64) ([]HealthCheckLog, error) {
	rows, err := q.db.QueryContext(ctx, listRecentHealthChecks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HealthCheckLog{}
	for rows.Next() {
		var i HealthCheckLog
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Model,
			&i.Success,
			&i.HttpStatus,
			&i.ResponseTimeMs,
			&i.Message,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
