// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createMcpSyncTarget = `-- name: CreateMcpSyncTarget :one
INSERT INTO mcp_sync_targets (
    client, config_path, label, enabled, last_sync_status, created_at, updated_at
) VALUES (?, ?, ?, ?, '', ?, ?)
RETURNING id, client, config_path, label, enabled, last_synced_at, last_sync_status, created_at, updated_at
`

type CreateMcpSyncTargetParams struct {
	Client     string `json:"client"`
	ConfigPath string `json:"config_path"`
	Label      string `json:"label"`
	Enabled    int64  `json:"enabled"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

func (q *Queries) CreateMcpSyncTarget(ctx context.Context, arg CreateMcpSyncTargetParams) (McpSyncTarget, error) {
	row := q.db.QueryRowContext(ctx, createMcpSyncTarget,
		arg.Client,
		arg.ConfigPath,
		arg.Label,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i McpSyncTarget
	err := row.Scan(
		&i.ID,
		&i.Client,
		&i.ConfigPath,
		&i.Label,
		&i.Enabled,
		&i.LastSyncedAt,
		&i.LastSyncStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMcpServer = `-- name: DeleteMcpServer :exec
DELETE FROM mcp_servers WHERE id = ?
`

func (q *Queries) DeleteMcpServer(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMcpServer, id)
	return err
}

const deleteMcpSyncTarget = `-- name: DeleteMcpSyncTarget :exec
DELETE FROM mcp_sync_targets WHERE id = ?
`

func (q *Queries) DeleteMcpSyncTarget(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMcpSyncTarget, id)
	return err
}

const getMcpServer = `-- name: GetMcpServer :one
SELECT id, name, spec_json, description, homepage, docs, tags_json, enabled_codex, enabled_claude, created_at, updated_at FROM mcp_servers WHERE id = ?
`

func (q *Queries) GetMcpServer(ctx context.Context, id string) (McpServer, error) {
	row := q.db.QueryRowContext(ctx, getMcpServer, id)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpecJson,
		&i.Description,
		&i.Homepage,
		&i.Docs,
		&i.TagsJson,
		&i.EnabledCodex,
		&i.EnabledClaude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMcpSyncTarget = `-- name: GetMcpSyncTarget :one
SELECT id, client, config_path, label, enabled, last_synced_at, last_sync_status, created_at, updated_at FROM mcp_sync_targets WHERE id = ?
`

func (q *Queries) GetMcpSyncTarget(ctx context.Context, id int64) (McpSyncTarget, error) {
	row := q.db.QueryRowContext(ctx, getMcpSyncTarget, id)
	var i McpSyncTarget
	err := row.Scan(
		&i.ID,
		&i.Client,
		&i.ConfigPath,
		&i.Label,
		&i.Enabled,
		&i.LastSyncedAt,
		&i.LastSyncStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledMcpSyncTargets = `-- name: ListEnabledMcpSyncTargets :many
SELECT id, client, config_path, label, enabled, last_synced_at, last_sync_status, created_at, updated_at FROM mcp_sync_targets WHERE enabled = 1 ORDER BY id
`

func (q *Queries) ListEnabledMcpSyncTargets(ctx context.Context) ([]McpSyncTarget, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledMcpSyncTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpSyncTarget{}
	for rows.Next() {
		var i McpSyncTarget
		if err := rows.Scan(
			&i.ID,
			&i.Client,
			&i.ConfigPath,
			&i.Label,
			&i.Enabled,
			&i.LastSyncedAt,
			&i.LastSyncStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMcpServers = `-- name: ListMcpServers :many

SELECT id, name, spec_json, description, homepage, docs, tags_json, enabled_codex, enabled_claude, created_at, updated_at FROM mcp_servers ORDER BY id
`

// mcp queries. ASCII-only comments.
func (q *Queries) ListMcpServers(ctx context.Context) ([]McpServer, error) {
	rows, err := q.db.QueryContext(ctx, listMcpServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpServer{}
	for rows.Next() {
		var i McpServer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SpecJson,
			&i.Description,
			&i.Homepage,
			&i.Docs,
			&i.TagsJson,
			&i.EnabledCodex,
			&i.EnabledClaude,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMcpSyncTargets = `-- name: ListMcpSyncTargets :many
SELECT id, client, config_path, label, enabled, last_synced_at, last_sync_status, created_at, updated_at FROM mcp_sync_targets ORDER BY id
`

func (q *Queries) ListMcpSyncTargets(ctx context.Context) ([]McpSyncTarget, error) {
	rows, err := q.db.QueryContext(ctx, listMcpSyncTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpSyncTarget{}
	for rows.Next() {
		var i McpSyncTarget
		if err := rows.Scan(
			&i.ID,
			&i.Client,
			&i.ConfigPath,
			&i.Label,
			&i.Enabled,
			&i.LastSyncedAt,
			&i.LastSyncStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMcpServerToggle = `-- name: SetMcpServerToggle :exec
UPDATE mcp_servers SET enabled_codex = ?, enabled_claude = ?, updated_at = ? WHERE id = ?
`

type SetMcpServerToggleParams struct {
	EnabledCodex  int64  `json:"enabled_codex"`
	EnabledClaude int64  `json:"enabled_claude"`
	UpdatedAt     string `json:"updated_at"`
	ID            string `json:"id"`
}

func (q *Queries) SetMcpServerToggle(ctx context.Context, arg SetMcpServerToggleParams) error {
	_, err := q.db.ExecContext(ctx, setMcpServerToggle,
		arg.EnabledCodex,
		arg.EnabledClaude,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setMcpSyncTargetStatus = `-- name: SetMcpSyncTargetStatus :exec
UPDATE mcp_sync_targets SET last_synced_at = ?, last_sync_status = ?, updated_at = ? WHERE id = ?
`

type SetMcpSyncTargetStatusParams struct {
	LastSyncedAt   sql.NullString `json:"last_synced_at"`
	LastSyncStatus string         `json:"last_sync_status"`
	UpdatedAt      string         `json:"updated_at"`
	ID             int64          `json:"id"`
}

func (q *Queries) SetMcpSyncTargetStatus(ctx context.Context, arg SetMcpSyncTargetStatusParams) error {
	_, err := q.db.ExecContext(ctx, setMcpSyncTargetStatus,
		arg.LastSyncedAt,
		arg.LastSyncStatus,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateMcpSyncTarget = `-- name: UpdateMcpSyncTarget :exec
UPDATE mcp_sync_targets SET client = ?, config_path = ?, label = ?, enabled = ?, updated_at = ? WHERE id = ?
`

type UpdateMcpSyncTargetParams struct {
	Client     string `json:"client"`
	ConfigPath string `json:"config_path"`
	Label      string `json:"label"`
	Enabled    int64  `json:"enabled"`
	UpdatedAt  string `json:"updated_at"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateMcpSyncTarget(ctx context.Context, arg UpdateMcpSyncTargetParams) error {
	_, err := q.db.ExecContext(ctx, updateMcpSyncTarget,
		arg.Client,
		arg.ConfigPath,
		arg.Label,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertMcpServer = `-- name: UpsertMcpServer :exec
INSERT INTO mcp_servers (
    id, name, spec_json, description, homepage, docs, tags_json,
    enabled_codex, enabled_claude, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    spec_json = excluded.spec_json,
    description = excluded.description,
    homepage = excluded.homepage,
    docs = excluded.docs,
    tags_json = excluded.tags_json,
    enabled_codex = excluded.enabled_codex,
    enabled_claude = excluded.enabled_claude,
    updated_at = excluded.updated_at
`

type UpsertMcpServerParams struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	SpecJson      string `json:"spec_json"`
	Description   string `json:"description"`
	Homepage      string `json:"homepage"`
	Docs          string `json:"docs"`
	TagsJson      string `json:"tags_json"`
	EnabledCodex  int64  `json:"enabled_codex"`
	EnabledClaude int64  `json:"enabled_claude"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

func (q *Queries) UpsertMcpServer(ctx context.Context, arg UpsertMcpServerParams) error {
	_, err := q.db.ExecContext(ctx, upsertMcpServer,
		arg.ID,
		arg.Name,
		arg.SpecJson,
		arg.Description,
		arg.Homepage,
		arg.Docs,
		arg.TagsJson,
		arg.EnabledCodex,
		arg.EnabledClaude,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
