// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
)

type Ability struct {
	GroupName     string `json:"group_name"`
	AliasModel    string `json:"alias_model"`
	ChannelID     int64  `json:"channel_id"`
	UpstreamModel string `json:"upstream_model"`
	Priority      int64  `json:"priority"`
	Weight        int64  `json:"weight"`
	Enabled       int64  `json:"enabled"`
}

type ApiKey struct {
	ID         int64          `json:"id"`
	Hash       string         `json:"hash"`
	Name       string         `json:"name"`
	GroupName  string         `json:"group_name"`
	Enabled    int64          `json:"enabled"`
	CreatedAt  string         `json:"created_at"`
	LastUsedAt sql.NullString `json:"last_used_at"`
}

type Channel struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	Enabled      int64  `json:"enabled"`
	Platform     string `json:"platform"`
	Type         string `json:"type"`
	BaseUrl      string `json:"base_url"`
	GroupName    string `json:"group_name"`
	Priority     int64  `json:"priority"`
	Weight       int64  `json:"weight"`
	Models       string `json:"models"`
	ModelMapping string `json:"model_mapping"`
	Prefix       string `json:"prefix"`
	ProxyUrl     string `json:"proxy_url"`
	Status       string `json:"status"`
	ErrorMessage string `json:"error_message"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type ChannelModelHealth struct {
	ChannelID           int64          `json:"channel_id"`
	Model               string         `json:"model"`
	IsHealthy           int64          `json:"is_healthy"`
	ConsecutiveFailures int64          `json:"consecutive_failures"`
	LastSuccessAt       sql.NullString `json:"last_success_at"`
	LastFailureAt       sql.NullString `json:"last_failure_at"`
	LastError           string         `json:"last_error"`
	CooldownUntil       sql.NullString `json:"cooldown_until"`
	UpdatedAt           string         `json:"updated_at"`
}

type HealthCheckLog struct {
	ID             int64  `json:"id"`
	ChannelID      int64  `json:"channel_id"`
	Model          string `json:"model"`
	Success        int64  `json:"success"`
	HttpStatus     int64  `json:"http_status"`
	ResponseTimeMs int64  `json:"response_time_ms"`
	Message        string `json:"message"`
	CheckedAt      string `json:"checked_at"`
}

type McpServer struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	SpecJson      string `json:"spec_json"`
	Description   string `json:"description"`
	Homepage      string `json:"homepage"`
	Docs          string `json:"docs"`
	TagsJson      string `json:"tags_json"`
	EnabledCodex  int64  `json:"enabled_codex"`
	EnabledClaude int64  `json:"enabled_claude"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

type McpSyncTarget struct {
	ID             int64          `json:"id"`
	Client         string         `json:"client"`
	ConfigPath     string         `json:"config_path"`
	Label          string         `json:"label"`
	Enabled        int64          `json:"enabled"`
	LastSyncedAt   sql.NullString `json:"last_synced_at"`
	LastSyncStatus string         `json:"last_sync_status"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

type Meta struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type ModelPricing struct {
	ModelID                 string `json:"model_id"`
	InputPerMillion         string `json:"input_per_million"`
	OutputPerMillion        string `json:"output_per_million"`
	CacheReadPerMillion     string `json:"cache_read_per_million"`
	CacheCreationPerMillion string `json:"cache_creation_per_million"`
	Source                  string `json:"source"`
	UpdatedAt               string `json:"updated_at"`
}

type RequestLog struct {
	ID                  int64         `json:"id"`
	RequestID           string        `json:"request_id"`
	CreatedAt           string        `json:"created_at"`
	ApiKeyID            int64         `json:"api_key_id"`
	ChannelID           int64         `json:"channel_id"`
	UserID              int64         `json:"user_id"`
	GroupName           string        `json:"group_name"`
	RequestedModel      string        `json:"requested_model"`
	UpstreamModel       string        `json:"upstream_model"`
	EndpointFormat      string        `json:"endpoint_format"`
	IsStream            int64         `json:"is_stream"`
	InputTokens         int64         `json:"input_tokens"`
	OutputTokens        int64         `json:"output_tokens"`
	ReasoningTokens     int64         `json:"reasoning_tokens"`
	CacheReadTokens     int64         `json:"cache_read_tokens"`
	CacheCreationTokens int64         `json:"cache_creation_tokens"`
	TotalTokens         int64         `json:"total_tokens"`
	LatencyMs           int64         `json:"latency_ms"`
	FirstTokenMs        sql.NullInt64 `json:"first_token_ms"`
	StatusCode          int64         `json:"status_code"`
	IsError             int64         `json:"is_error"`
	ErrorType           string        `json:"error_type"`
	ErrorMessage        string        `json:"error_message"`
	SessionID           string        `json:"session_id"`
	UsageSource         string        `json:"usage_source"`
}

type UsageDailyRollup struct {
	BucketDate          string `json:"bucket_date"`
	ChannelID           int64  `json:"channel_id"`
	RequestedModel      string `json:"requested_model"`
	RequestCount        int64  `json:"request_count"`
	SuccessCount        int64  `json:"success_count"`
	ErrorCount          int64  `json:"error_count"`
	InputTokens         int64  `json:"input_tokens"`
	OutputTokens        int64  `json:"output_tokens"`
	CacheReadTokens     int64  `json:"cache_read_tokens"`
	CacheCreationTokens int64  `json:"cache_creation_tokens"`
	ReasoningTokens     int64  `json:"reasoning_tokens"`
	SumLatencyMs        int64  `json:"sum_latency_ms"`
	SumFirstTokenMs     int64  `json:"sum_first_token_ms"`
	CountFirstToken     int64  `json:"count_first_token"`
}

type UsageHourlyRollup struct {
	BucketHour          string `json:"bucket_hour"`
	ChannelID           int64  `json:"channel_id"`
	ApiKeyID            int64  `json:"api_key_id"`
	RequestedModel      string `json:"requested_model"`
	RequestCount        int64  `json:"request_count"`
	SuccessCount        int64  `json:"success_count"`
	ErrorCount          int64  `json:"error_count"`
	InputTokens         int64  `json:"input_tokens"`
	OutputTokens        int64  `json:"output_tokens"`
	CacheReadTokens     int64  `json:"cache_read_tokens"`
	CacheCreationTokens int64  `json:"cache_creation_tokens"`
	ReasoningTokens     int64  `json:"reasoning_tokens"`
	SumLatencyMs        int64  `json:"sum_latency_ms"`
	SumFirstTokenMs     int64  `json:"sum_first_token_ms"`
	CountFirstToken     int64  `json:"count_first_token"`
}
