// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
)

type Ability struct {
	GroupName     string `json:"group_name"`
	AliasModel    string `json:"alias_model"`
	ChannelID     int64  `json:"channel_id"`
	UpstreamModel string `json:"upstream_model"`
	Priority      int64  `json:"priority"`
	Weight        int64  `json:"weight"`
	Enabled       int64  `json:"enabled"`
}

type ApiKey struct {
	ID         int64          `json:"id"`
	Hash       string         `json:"hash"`
	Name       string         `json:"name"`
	GroupName  string         `json:"group_name"`
	Enabled    int64          `json:"enabled"`
	CreatedAt  string         `json:"created_at"`
	LastUsedAt sql.NullString `json:"last_used_at"`
}

type Channel struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	Enabled      int64  `json:"enabled"`
	Platform     string `json:"platform"`
	Type         string `json:"type"`
	BaseUrl      string `json:"base_url"`
	GroupName    string `json:"group_name"`
	Priority     int64  `json:"priority"`
	Weight       int64  `json:"weight"`
	Models       string `json:"models"`
	ModelMapping string `json:"model_mapping"`
	Prefix       string `json:"prefix"`
	ProxyUrl     string `json:"proxy_url"`
	Status       string `json:"status"`
	ErrorMessage string `json:"error_message"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type ChannelModelHealth struct {
	ChannelID           int64          `json:"channel_id"`
	Model               string         `json:"model"`
	IsHealthy           int64          `json:"is_healthy"`
	ConsecutiveFailures int64          `json:"consecutive_failures"`
	LastSuccessAt       sql.NullString `json:"last_success_at"`
	LastFailureAt       sql.NullString `json:"last_failure_at"`
	LastError           string         `json:"last_error"`
	CooldownUntil       sql.NullString `json:"cooldown_until"`
	UpdatedAt           string         `json:"updated_at"`
}

type Meta struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}
