// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pricing.sql

package dbgen

import (
	"context"
)

const deleteModelPricing = `-- name: DeleteModelPricing :exec
DELETE FROM model_pricing WHERE model_id = ?
`

func (q *Queries) DeleteModelPricing(ctx context.Context, modelID string) error {
	_, err := q.db.ExecContext(ctx, deleteModelPricing, modelID)
	return err
}

const getModelPricing = `-- name: GetModelPricing :one
SELECT model_id, input_per_million, output_per_million, cache_read_per_million, cache_creation_per_million, source, updated_at FROM model_pricing WHERE model_id = ?
`

func (q *Queries) GetModelPricing(ctx context.Context, modelID string) (ModelPricing, error) {
	row := q.db.QueryRowContext(ctx, getModelPricing, modelID)
	var i ModelPricing
	err := row.Scan(
		&i.ModelID,
		&i.InputPerMillion,
		&i.OutputPerMillion,
		&i.CacheReadPerMillion,
		&i.CacheCreationPerMillion,
		&i.Source,
		&i.UpdatedAt,
	)
	return i, err
}

const listModelPricing = `-- name: ListModelPricing :many

SELECT model_id, input_per_million, output_per_million, cache_read_per_million, cache_creation_per_million, source, updated_at FROM model_pricing ORDER BY model_id
`

// model_pricing queries. ASCII-only comments.
func (q *Queries) ListModelPricing(ctx context.Context) ([]ModelPricing, error) {
	rows, err := q.db.QueryContext(ctx, listModelPricing)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelPricing{}
	for rows.Next() {
		var i ModelPricing
		if err := rows.Scan(
			&i.ModelID,
			&i.InputPerMillion,
			&i.OutputPerMillion,
			&i.CacheReadPerMillion,
			&i.CacheCreationPerMillion,
			&i.Source,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedModelPricing = `-- name: SeedModelPricing :exec
INSERT INTO model_pricing (
    model_id, input_per_million, output_per_million,
    cache_read_per_million, cache_creation_per_million, source, updated_at
) VALUES (?, ?, ?, ?, ?, 'seed', ?)
ON CONFLICT(model_id) DO NOTHING
`

type SeedModelPricingParams struct {
	ModelID                 string `json:"model_id"`
	InputPerMillion         string `json:"input_per_million"`
	OutputPerMillion        string `json:"output_per_million"`
	CacheReadPerMillion     string `json:"cache_read_per_million"`
	CacheCreationPerMillion string `json:"cache_creation_per_million"`
	UpdatedAt               string `json:"updated_at"`
}

// Seed insert: only when absent; never overwrites an admin-edited row.
func (q *Queries) SeedModelPricing(ctx context.Context, arg SeedModelPricingParams) error {
	_, err := q.db.ExecContext(ctx, seedModelPricing,
		arg.ModelID,
		arg.InputPerMillion,
		arg.OutputPerMillion,
		arg.CacheReadPerMillion,
		arg.CacheCreationPerMillion,
		arg.UpdatedAt,
	)
	return err
}

const upsertModelPricing = `-- name: UpsertModelPricing :exec
INSERT INTO model_pricing (
    model_id, input_per_million, output_per_million,
    cache_read_per_million, cache_creation_per_million, source, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(model_id) DO UPDATE SET
    input_per_million = excluded.input_per_million,
    output_per_million = excluded.output_per_million,
    cache_read_per_million = excluded.cache_read_per_million,
    cache_creation_per_million = excluded.cache_creation_per_million,
    source = excluded.source,
    updated_at = excluded.updated_at
`

type UpsertModelPricingParams struct {
	ModelID                 string `json:"model_id"`
	InputPerMillion         string `json:"input_per_million"`
	OutputPerMillion        string `json:"output_per_million"`
	CacheReadPerMillion     string `json:"cache_read_per_million"`
	CacheCreationPerMillion string `json:"cache_creation_per_million"`
	Source                  string `json:"source"`
	UpdatedAt               string `json:"updated_at"`
}

// Admin override: replaces values and marks source.
func (q *Queries) UpsertModelPricing(ctx context.Context, arg UpsertModelPricingParams) error {
	_, err := q.db.ExecContext(ctx, upsertModelPricing,
		arg.ModelID,
		arg.InputPerMillion,
		arg.OutputPerMillion,
		arg.CacheReadPerMillion,
		arg.CacheCreationPerMillion,
		arg.Source,
		arg.UpdatedAt,
	)
	return err
}
