// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: request_logs.sql

package dbgen

import (
	"context"
	"database/sql"
)

const breakdownErrorTypeRange = `-- name: BreakdownErrorTypeRange :many
SELECT
    error_type AS error_type,
    CAST(COUNT(*) AS INTEGER) AS request_count
FROM request_logs
WHERE created_at >= ? AND is_error = 1
GROUP BY error_type
ORDER BY COUNT(*) DESC
`

type BreakdownErrorTypeRangeRow struct {
	ErrorType    string `json:"error_type"`
	RequestCount int64  `json:"request_count"`
}

// Error-type breakdown comes from facts (rollups do not carry error_type).
func (q *Queries) BreakdownErrorTypeRange(ctx context.Context, createdAt string) ([]BreakdownErrorTypeRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, breakdownErrorTypeRange, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BreakdownErrorTypeRangeRow{}
	for rows.Next() {
		var i BreakdownErrorTypeRangeRow
		if err := rows.Scan(&i.ErrorType, &i.RequestCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRequestLogsFiltered = `-- name: CountRequestLogsFiltered :one
SELECT CAST(COUNT(*) AS INTEGER) FROM request_logs
WHERE (?1 IS NULL OR request_id = ?1)
  AND (?2 IS NULL OR api_key_id = ?2)
  AND (?3 IS NULL OR channel_id = ?3)
  AND (?4 IS NULL OR requested_model = ?4)
`

type CountRequestLogsFilteredParams struct {
	RequestID      interface{} `json:"request_id"`
	ApiKeyID       interface{} `json:"api_key_id"`
	ChannelID      interface{} `json:"channel_id"`
	RequestedModel interface{} `json:"requested_model"`
}

func (q *Queries) CountRequestLogsFiltered(ctx context.Context, arg CountRequestLogsFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRequestLogsFiltered,
		arg.RequestID,
		arg.ApiKeyID,
		arg.ChannelID,
		arg.RequestedModel,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteRequestLogsBefore = `-- name: DeleteRequestLogsBefore :execrows
DELETE FROM request_logs WHERE created_at < ?
`

func (q *Queries) DeleteRequestLogsBefore(ctx context.Context, createdAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRequestLogsBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertRequestLog = `-- name: InsertRequestLog :exec

INSERT INTO request_logs (
    request_id, created_at, api_key_id, channel_id, user_id, group_name,
    requested_model, upstream_model, endpoint_format, is_stream,
    input_tokens, output_tokens, reasoning_tokens, cache_read_tokens, cache_creation_tokens, total_tokens,
    latency_ms, first_token_ms, status_code, is_error, error_type, error_message, session_id, usage_source
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertRequestLogParams struct {
	RequestID           string        `json:"request_id"`
	CreatedAt           string        `json:"created_at"`
	ApiKeyID            int64         `json:"api_key_id"`
	ChannelID           int64         `json:"channel_id"`
	UserID              int64         `json:"user_id"`
	GroupName           string        `json:"group_name"`
	RequestedModel      string        `json:"requested_model"`
	UpstreamModel       string        `json:"upstream_model"`
	EndpointFormat      string        `json:"endpoint_format"`
	IsStream            int64         `json:"is_stream"`
	InputTokens         int64         `json:"input_tokens"`
	OutputTokens        int64         `json:"output_tokens"`
	ReasoningTokens     int64         `json:"reasoning_tokens"`
	CacheReadTokens     int64         `json:"cache_read_tokens"`
	CacheCreationTokens int64         `json:"cache_creation_tokens"`
	TotalTokens         int64         `json:"total_tokens"`
	LatencyMs           int64         `json:"latency_ms"`
	FirstTokenMs        sql.NullInt64 `json:"first_token_ms"`
	StatusCode          int64         `json:"status_code"`
	IsError             int64         `json:"is_error"`
	ErrorType           string        `json:"error_type"`
	ErrorMessage        string        `json:"error_message"`
	SessionID           string        `json:"session_id"`
	UsageSource         string        `json:"usage_source"`
}

// request_logs queries. ASCII-only comments (sqlc parser).
func (q *Queries) InsertRequestLog(ctx context.Context, arg InsertRequestLogParams) error {
	_, err := q.db.ExecContext(ctx, insertRequestLog,
		arg.RequestID,
		arg.CreatedAt,
		arg.ApiKeyID,
		arg.ChannelID,
		arg.UserID,
		arg.GroupName,
		arg.RequestedModel,
		arg.UpstreamModel,
		arg.EndpointFormat,
		arg.IsStream,
		arg.InputTokens,
		arg.OutputTokens,
		arg.ReasoningTokens,
		arg.CacheReadTokens,
		arg.CacheCreationTokens,
		arg.TotalTokens,
		arg.LatencyMs,
		arg.FirstTokenMs,
		arg.StatusCode,
		arg.IsError,
		arg.ErrorType,
		arg.ErrorMessage,
		arg.SessionID,
		arg.UsageSource,
	)
	return err
}

const listRequestLogsFiltered = `-- name: ListRequestLogsFiltered :many
SELECT id, request_id, created_at, api_key_id, channel_id, user_id, group_name, requested_model, upstream_model, endpoint_format, is_stream, input_tokens, output_tokens, reasoning_tokens, cache_read_tokens, cache_creation_tokens, total_tokens, latency_ms, first_token_ms, status_code, is_error, error_type, error_message, session_id, usage_source FROM request_logs
WHERE (?1 IS NULL OR request_id = ?1)
  AND (?2 IS NULL OR api_key_id = ?2)
  AND (?3 IS NULL OR channel_id = ?3)
  AND (?4 IS NULL OR requested_model = ?4)
ORDER BY created_at DESC, id DESC
LIMIT ?6 OFFSET ?5
`

type ListRequestLogsFilteredParams struct {
	RequestID      interface{} `json:"request_id"`
	ApiKeyID       interface{} `json:"api_key_id"`
	ChannelID      interface{} `json:"channel_id"`
	RequestedModel interface{} `json:"requested_model"`
	Off            int64       `json:"off"`
	Lim            int64       `json:"lim"`
}

// Optional filters via sqlc.narg (NULL = no filter). Paged, newest first.
func (q *Queries) ListRequestLogsFiltered(ctx context.Context, arg ListRequestLogsFilteredParams) ([]RequestLog, error) {
	rows, err := q.db.QueryContext(ctx, listRequestLogsFiltered,
		arg.RequestID,
		arg.ApiKeyID,
		arg.ChannelID,
		arg.RequestedModel,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestLog{}
	for rows.Next() {
		var i RequestLog
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.CreatedAt,
			&i.ApiKeyID,
			&i.ChannelID,
			&i.UserID,
			&i.GroupName,
			&i.RequestedModel,
			&i.UpstreamModel,
			&i.EndpointFormat,
			&i.IsStream,
			&i.InputTokens,
			&i.OutputTokens,
			&i.ReasoningTokens,
			&i.CacheReadTokens,
			&i.CacheCreationTokens,
			&i.TotalTokens,
			&i.LatencyMs,
			&i.FirstTokenMs,
			&i.StatusCode,
			&i.IsError,
			&i.ErrorType,
			&i.ErrorMessage,
			&i.SessionID,
			&i.UsageSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
