// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rollups.sql

package dbgen

import (
	"context"
)

const breakdownHourlyByApiKey = `-- name: BreakdownHourlyByApiKey :many
SELECT
    CAST(api_key_id AS INTEGER) AS dim,
    CAST(COALESCE(SUM(request_count), 0) AS INTEGER) AS request_count,
    CAST(COALESCE(SUM(error_count), 0) AS INTEGER) AS error_count,
    CAST(COALESCE(SUM(input_tokens), 0) AS INTEGER) AS input_tokens,
    CAST(COALESCE(SUM(output_tokens), 0) AS INTEGER) AS output_tokens,
    CAST(COALESCE(SUM(cache_read_tokens), 0) AS INTEGER) AS cache_read_tokens,
    CAST(COALESCE(SUM(cache_creation_tokens), 0) AS INTEGER) AS cache_creation_tokens,
    CAST(COALESCE(SUM(reasoning_tokens), 0) AS INTEGER) AS reasoning_tokens,
    CAST(COALESCE(SUM(sum_latency_ms), 0) AS INTEGER) AS sum_latency_ms
FROM usage_hourly_rollups
WHERE bucket_hour >= ?
GROUP BY api_key_id
ORDER BY SUM(input_tokens) + SUM(output_tokens) DESC
`

type BreakdownHourlyByApiKeyRow struct {
	Dim                 int64 `json:"dim"`
	RequestCount        int64 `json:"request_count"`
	ErrorCount          int64 `json:"error_count"`
	InputTokens         int64 `json:"input_tokens"`
	OutputTokens        int64 `json:"output_tokens"`
	CacheReadTokens     int64 `json:"cache_read_tokens"`
	CacheCreationTokens int64 `json:"cache_creation_tokens"`
	ReasoningTokens     int64 `json:"reasoning_tokens"`
	SumLatencyMs        int64 `json:"sum_latency_ms"`
}

func (q *Queries) BreakdownHourlyByApiKey(ctx context.Context, bucketHour string) ([]BreakdownHourlyByApiKeyRow, error) {
	rows, err := q.db.QueryContext(ctx, breakdownHourlyByApiKey, bucketHour)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BreakdownHourlyByApiKeyRow{}
	for rows.Next() {
		var i BreakdownHourlyByApiKeyRow
		if err := rows.Scan(
			&i.Dim,
			&i.RequestCount,
			&i.ErrorCount,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheCreationTokens,
			&i.ReasoningTokens,
			&i.SumLatencyMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const breakdownHourlyByChannel = `-- name: BreakdownHourlyByChannel :many
SELECT
    CAST(channel_id AS INTEGER) AS dim,
    CAST(COALESCE(SUM(request_count), 0) AS INTEGER) AS request_count,
    CAST(COALESCE(SUM(error_count), 0) AS INTEGER) AS error_count,
    CAST(COALESCE(SUM(input_tokens), 0) AS INTEGER) AS input_tokens,
    CAST(COALESCE(SUM(output_tokens), 0) AS INTEGER) AS output_tokens,
    CAST(COALESCE(SUM(cache_read_tokens), 0) AS INTEGER) AS cache_read_tokens,
    CAST(COALESCE(SUM(cache_creation_tokens), 0) AS INTEGER) AS cache_creation_tokens,
    CAST(COALESCE(SUM(reasoning_tokens), 0) AS INTEGER) AS reasoning_tokens,
    CAST(COALESCE(SUM(sum_latency_ms), 0) AS INTEGER) AS sum_latency_ms
FROM usage_hourly_rollups
WHERE bucket_hour >= ?
GROUP BY channel_id
ORDER BY SUM(input_tokens) + SUM(output_tokens) DESC
`

type BreakdownHourlyByChannelRow struct {
	Dim                 int64 `json:"dim"`
	RequestCount        int64 `json:"request_count"`
	ErrorCount          int64 `json:"error_count"`
	InputTokens         int64 `json:"input_tokens"`
	OutputTokens        int64 `json:"output_tokens"`
	CacheReadTokens     int64 `json:"cache_read_tokens"`
	CacheCreationTokens int64 `json:"cache_creation_tokens"`
	ReasoningTokens     int64 `json:"reasoning_tokens"`
	SumLatencyMs        int64 `json:"sum_latency_ms"`
}

func (q *Queries) BreakdownHourlyByChannel(ctx context.Context, bucketHour string) ([]BreakdownHourlyByChannelRow, error) {
	rows, err := q.db.QueryContext(ctx, breakdownHourlyByChannel, bucketHour)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BreakdownHourlyByChannelRow{}
	for rows.Next() {
		var i BreakdownHourlyByChannelRow
		if err := rows.Scan(
			&i.Dim,
			&i.RequestCount,
			&i.ErrorCount,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheCreationTokens,
			&i.ReasoningTokens,
			&i.SumLatencyMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const breakdownHourlyByModel = `-- name: BreakdownHourlyByModel :many
SELECT
    requested_model AS dim,
    CAST(COALESCE(SUM(request_count), 0) AS INTEGER) AS request_count,
    CAST(COALESCE(SUM(error_count), 0) AS INTEGER) AS error_count,
    CAST(COALESCE(SUM(input_tokens), 0) AS INTEGER) AS input_tokens,
    CAST(COALESCE(SUM(output_tokens), 0) AS INTEGER) AS output_tokens,
    CAST(COALESCE(SUM(cache_read_tokens), 0) AS INTEGER) AS cache_read_tokens,
    CAST(COALESCE(SUM(cache_creation_tokens), 0) AS INTEGER) AS cache_creation_tokens,
    CAST(COALESCE(SUM(reasoning_tokens), 0) AS INTEGER) AS reasoning_tokens,
    CAST(COALESCE(SUM(sum_latency_ms), 0) AS INTEGER) AS sum_latency_ms
FROM usage_hourly_rollups
WHERE bucket_hour >= ?
GROUP BY requested_model
ORDER BY SUM(input_tokens) + SUM(output_tokens) DESC
`

type BreakdownHourlyByModelRow struct {
	Dim                 string `json:"dim"`
	RequestCount        int64  `json:"request_count"`
	ErrorCount          int64  `json:"error_count"`
	InputTokens         int64  `json:"input_tokens"`
	OutputTokens        int64  `json:"output_tokens"`
	CacheReadTokens     int64  `json:"cache_read_tokens"`
	CacheCreationTokens int64  `json:"cache_creation_tokens"`
	ReasoningTokens     int64  `json:"reasoning_tokens"`
	SumLatencyMs        int64  `json:"sum_latency_ms"`
}

func (q *Queries) BreakdownHourlyByModel(ctx context.Context, bucketHour string) ([]BreakdownHourlyByModelRow, error) {
	rows, err := q.db.QueryContext(ctx, breakdownHourlyByModel, bucketHour)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BreakdownHourlyByModelRow{}
	for rows.Next() {
		var i BreakdownHourlyByModelRow
		if err := rows.Scan(
			&i.Dim,
			&i.RequestCount,
			&i.ErrorCount,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheCreationTokens,
			&i.ReasoningTokens,
			&i.SumLatencyMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumHourlyRange = `-- name: SumHourlyRange :one
SELECT
    CAST(COALESCE(SUM(request_count), 0) AS INTEGER) AS request_count,
    CAST(COALESCE(SUM(success_count), 0) AS INTEGER) AS success_count,
    CAST(COALESCE(SUM(error_count), 0) AS INTEGER) AS error_count,
    CAST(COALESCE(SUM(input_tokens), 0) AS INTEGER) AS input_tokens,
    CAST(COALESCE(SUM(output_tokens), 0) AS INTEGER) AS output_tokens,
    CAST(COALESCE(SUM(cache_read_tokens), 0) AS INTEGER) AS cache_read_tokens,
    CAST(COALESCE(SUM(cache_creation_tokens), 0) AS INTEGER) AS cache_creation_tokens,
    CAST(COALESCE(SUM(reasoning_tokens), 0) AS INTEGER) AS reasoning_tokens,
    CAST(COALESCE(SUM(sum_latency_ms), 0) AS INTEGER) AS sum_latency_ms,
    CAST(COALESCE(SUM(sum_first_token_ms), 0) AS INTEGER) AS sum_first_token_ms,
    CAST(COALESCE(SUM(count_first_token), 0) AS INTEGER) AS count_first_token
FROM usage_hourly_rollups
WHERE bucket_hour >= ?
`

type SumHourlyRangeRow struct {
	RequestCount        int64 `json:"request_count"`
	SuccessCount        int64 `json:"success_count"`
	ErrorCount          int64 `json:"error_count"`
	InputTokens         int64 `json:"input_tokens"`
	OutputTokens        int64 `json:"output_tokens"`
	CacheReadTokens     int64 `json:"cache_read_tokens"`
	CacheCreationTokens int64 `json:"cache_creation_tokens"`
	ReasoningTokens     int64 `json:"reasoning_tokens"`
	SumLatencyMs        int64 `json:"sum_latency_ms"`
	SumFirstTokenMs     int64 `json:"sum_first_token_ms"`
	CountFirstToken     int64 `json:"count_first_token"`
}

func (q *Queries) SumHourlyRange(ctx context.Context, bucketHour string) (SumHourlyRangeRow, error) {
	row := q.db.QueryRowContext(ctx, sumHourlyRange, bucketHour)
	var i SumHourlyRangeRow
	err := row.Scan(
		&i.RequestCount,
		&i.SuccessCount,
		&i.ErrorCount,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheCreationTokens,
		&i.ReasoningTokens,
		&i.SumLatencyMs,
		&i.SumFirstTokenMs,
		&i.CountFirstToken,
	)
	return i, err
}

const timeseriesDaily = `-- name: TimeseriesDaily :many
SELECT
    bucket_date AS bucket,
    CAST(COALESCE(SUM(request_count), 0) AS INTEGER) AS request_count,
    CAST(COALESCE(SUM(success_count), 0) AS INTEGER) AS success_count,
    CAST(COALESCE(SUM(error_count), 0) AS INTEGER) AS error_count,
    CAST(COALESCE(SUM(input_tokens), 0) AS INTEGER) AS input_tokens,
    CAST(COALESCE(SUM(output_tokens), 0) AS INTEGER) AS output_tokens,
    CAST(COALESCE(SUM(sum_latency_ms), 0) AS INTEGER) AS sum_latency_ms,
    CAST(COALESCE(SUM(sum_first_token_ms), 0) AS INTEGER) AS sum_first_token_ms,
    CAST(COALESCE(SUM(count_first_token), 0) AS INTEGER) AS count_first_token
FROM usage_daily_rollups
WHERE bucket_date >= ?
GROUP BY bucket_date
ORDER BY bucket_date
`

type TimeseriesDailyRow struct {
	Bucket          string `json:"bucket"`
	RequestCount    int64  `json:"request_count"`
	SuccessCount    int64  `json:"success_count"`
	ErrorCount      int64  `json:"error_count"`
	InputTokens     int64  `json:"input_tokens"`
	OutputTokens    int64  `json:"output_tokens"`
	SumLatencyMs    int64  `json:"sum_latency_ms"`
	SumFirstTokenMs int64  `json:"sum_first_token_ms"`
	CountFirstToken int64  `json:"count_first_token"`
}

func (q *Queries) TimeseriesDaily(ctx context.Context, bucketDate string) ([]TimeseriesDailyRow, error) {
	rows, err := q.db.QueryContext(ctx, timeseriesDaily, bucketDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimeseriesDailyRow{}
	for rows.Next() {
		var i TimeseriesDailyRow
		if err := rows.Scan(
			&i.Bucket,
			&i.RequestCount,
			&i.SuccessCount,
			&i.ErrorCount,
			&i.InputTokens,
			&i.OutputTokens,
			&i.SumLatencyMs,
			&i.SumFirstTokenMs,
			&i.CountFirstToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const timeseriesHourly = `-- name: TimeseriesHourly :many
SELECT
    bucket_hour AS bucket,
    CAST(COALESCE(SUM(request_count), 0) AS INTEGER) AS request_count,
    CAST(COALESCE(SUM(success_count), 0) AS INTEGER) AS success_count,
    CAST(COALESCE(SUM(error_count), 0) AS INTEGER) AS error_count,
    CAST(COALESCE(SUM(input_tokens), 0) AS INTEGER) AS input_tokens,
    CAST(COALESCE(SUM(output_tokens), 0) AS INTEGER) AS output_tokens,
    CAST(COALESCE(SUM(sum_latency_ms), 0) AS INTEGER) AS sum_latency_ms,
    CAST(COALESCE(SUM(sum_first_token_ms), 0) AS INTEGER) AS sum_first_token_ms,
    CAST(COALESCE(SUM(count_first_token), 0) AS INTEGER) AS count_first_token
FROM usage_hourly_rollups
WHERE bucket_hour >= ?
GROUP BY bucket_hour
ORDER BY bucket_hour
`

type TimeseriesHourlyRow struct {
	Bucket          string `json:"bucket"`
	RequestCount    int64  `json:"request_count"`
	SuccessCount    int64  `json:"success_count"`
	ErrorCount      int64  `json:"error_count"`
	InputTokens     int64  `json:"input_tokens"`
	OutputTokens    int64  `json:"output_tokens"`
	SumLatencyMs    int64  `json:"sum_latency_ms"`
	SumFirstTokenMs int64  `json:"sum_first_token_ms"`
	CountFirstToken int64  `json:"count_first_token"`
}

func (q *Queries) TimeseriesHourly(ctx context.Context, bucketHour string) ([]TimeseriesHourlyRow, error) {
	rows, err := q.db.QueryContext(ctx, timeseriesHourly, bucketHour)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimeseriesHourlyRow{}
	for rows.Next() {
		var i TimeseriesHourlyRow
		if err := rows.Scan(
			&i.Bucket,
			&i.RequestCount,
			&i.SuccessCount,
			&i.ErrorCount,
			&i.InputTokens,
			&i.OutputTokens,
			&i.SumLatencyMs,
			&i.SumFirstTokenMs,
			&i.CountFirstToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyRollup = `-- name: UpsertDailyRollup :exec
INSERT INTO usage_daily_rollups (
    bucket_date, channel_id, requested_model,
    request_count, success_count, error_count,
    input_tokens, output_tokens, cache_read_tokens, cache_creation_tokens, reasoning_tokens,
    sum_latency_ms, sum_first_token_ms, count_first_token
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(bucket_date, channel_id, requested_model) DO UPDATE SET
    request_count = request_count + excluded.request_count,
    success_count = success_count + excluded.success_count,
    error_count = error_count + excluded.error_count,
    input_tokens = input_tokens + excluded.input_tokens,
    output_tokens = output_tokens + excluded.output_tokens,
    cache_read_tokens = cache_read_tokens + excluded.cache_read_tokens,
    cache_creation_tokens = cache_creation_tokens + excluded.cache_creation_tokens,
    reasoning_tokens = reasoning_tokens + excluded.reasoning_tokens,
    sum_latency_ms = sum_latency_ms + excluded.sum_latency_ms,
    sum_first_token_ms = sum_first_token_ms + excluded.sum_first_token_ms,
    count_first_token = count_first_token + excluded.count_first_token
`

type UpsertDailyRollupParams struct {
	BucketDate          string `json:"bucket_date"`
	ChannelID           int64  `json:"channel_id"`
	RequestedModel      string `json:"requested_model"`
	RequestCount        int64  `json:"request_count"`
	SuccessCount        int64  `json:"success_count"`
	ErrorCount          int64  `json:"error_count"`
	InputTokens         int64  `json:"input_tokens"`
	OutputTokens        int64  `json:"output_tokens"`
	CacheReadTokens     int64  `json:"cache_read_tokens"`
	CacheCreationTokens int64  `json:"cache_creation_tokens"`
	ReasoningTokens     int64  `json:"reasoning_tokens"`
	SumLatencyMs        int64  `json:"sum_latency_ms"`
	SumFirstTokenMs     int64  `json:"sum_first_token_ms"`
	CountFirstToken     int64  `json:"count_first_token"`
}

func (q *Queries) UpsertDailyRollup(ctx context.Context, arg UpsertDailyRollupParams) error {
	_, err := q.db.ExecContext(ctx, upsertDailyRollup,
		arg.BucketDate,
		arg.ChannelID,
		arg.RequestedModel,
		arg.RequestCount,
		arg.SuccessCount,
		arg.ErrorCount,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheCreationTokens,
		arg.ReasoningTokens,
		arg.SumLatencyMs,
		arg.SumFirstTokenMs,
		arg.CountFirstToken,
	)
	return err
}

const upsertHourlyRollup = `-- name: UpsertHourlyRollup :exec

INSERT INTO usage_hourly_rollups (
    bucket_hour, channel_id, api_key_id, requested_model,
    request_count, success_count, error_count,
    input_tokens, output_tokens, cache_read_tokens, cache_creation_tokens, reasoning_tokens,
    sum_latency_ms, sum_first_token_ms, count_first_token
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(bucket_hour, channel_id, api_key_id, requested_model) DO UPDATE SET
    request_count = request_count + excluded.request_count,
    success_count = success_count + excluded.success_count,
    error_count = error_count + excluded.error_count,
    input_tokens = input_tokens + excluded.input_tokens,
    output_tokens = output_tokens + excluded.output_tokens,
    cache_read_tokens = cache_read_tokens + excluded.cache_read_tokens,
    cache_creation_tokens = cache_creation_tokens + excluded.cache_creation_tokens,
    reasoning_tokens = reasoning_tokens + excluded.reasoning_tokens,
    sum_latency_ms = sum_latency_ms + excluded.sum_latency_ms,
    sum_first_token_ms = sum_first_token_ms + excluded.sum_first_token_ms,
    count_first_token = count_first_token + excluded.count_first_token
`

type UpsertHourlyRollupParams struct {
	BucketHour          string `json:"bucket_hour"`
	ChannelID           int64  `json:"channel_id"`
	ApiKeyID            int64  `json:"api_key_id"`
	RequestedModel      string `json:"requested_model"`
	RequestCount        int64  `json:"request_count"`
	SuccessCount        int64  `json:"success_count"`
	ErrorCount          int64  `json:"error_count"`
	InputTokens         int64  `json:"input_tokens"`
	OutputTokens        int64  `json:"output_tokens"`
	CacheReadTokens     int64  `json:"cache_read_tokens"`
	CacheCreationTokens int64  `json:"cache_creation_tokens"`
	ReasoningTokens     int64  `json:"reasoning_tokens"`
	SumLatencyMs        int64  `json:"sum_latency_ms"`
	SumFirstTokenMs     int64  `json:"sum_first_token_ms"`
	CountFirstToken     int64  `json:"count_first_token"`
}

// usage rollup queries. ASCII-only comments. Aggregates CAST to INTEGER for clean int64 generation.
func (q *Queries) UpsertHourlyRollup(ctx context.Context, arg UpsertHourlyRollupParams) error {
	_, err := q.db.ExecContext(ctx, upsertHourlyRollup,
		arg.BucketHour,
		arg.ChannelID,
		arg.ApiKeyID,
		arg.RequestedModel,
		arg.RequestCount,
		arg.SuccessCount,
		arg.ErrorCount,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheCreationTokens,
		arg.ReasoningTokens,
		arg.SumLatencyMs,
		arg.SumFirstTokenMs,
		arg.CountFirstToken,
	)
	return err
}
